* init-lang.el
:PROPERTIES:
:HEADER-ARGS: :tangle (concat temporary-file-directory "init-lang.el") :lexical t
:END:

** Headers
#+begin_src emacs-lisp
  ;;; init-lang.el ---   -*- lexical-binding: t; -*-

  ;;; Commentary:

  ;;; Code :
  (require 'init-custom)
#+end_src

** Flycheck
#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t
    :defer t
    ;;:hook (after-init . global-flycheck-mode)
    )
#+end_src

** LSP Mode
如使用 =cape= 和 =corfu= 代替 =company= ，则最后的重置 ~company-backends~ 略过。
目前仍然使用 =company= ，因此还需配置。
设置 =Eglot= 。
#+begin_src emacs-lisp
(use-package eglot
  :bind ("C-c e f" . eglot-format)
  :init
  (advice-add 'eglot-code-action-organize-imports :before #'eglot-format-buffer)
  (add-hook 'eglot-managed-mode-hook (lambda () (add-hook 'before-save-hook #'eglot-format-buffer)))
  (add-hook 'prog-mode-hook
      (lambda () (unless (member major-mode '(emacs-lisp-mode))
       (eglot-ensure)))))
#+end_src

** Tree Sitter
#begin_src emacs-lisp :tangle no
;; (use-package treesit
;; (when (and (fboundp 'treesit-available-p) (treesit-available-p))
;;   :mode (("\\(?:Dockerfile\\(?:\\..*\\)?\\|\\.[Dd]ockerfile\\)\\'" . dockerfile-ts-mode)
;;          ("\\.go\\'" . go-ts-mode)
;;          ("/go\\.mod\\'" . go-mod-ts-mode)
;;          ("\\.rs\\'" . rust-ts-mode)
;;          ("\\.ts\\'" . typescript-ts-mode)
;;          ("\\.y[a]?ml\\'" . yaml-ts-mode))
;;   :config (setq treesit-font-lock-level 4)
;;   ;; go-ts-mode indent 4 space
;;   (add-hook 'go-ts-mode-hook
;;             (lambda ()
;;               (setq go-ts-mode-indent-offset 4) ; indent width 4
;;               (setq tab-width 4)                ; tab width 4
;;               (setq indent-tabs-mode nil)))     ; indent not with tab
;;   :init
;;   (setq major-mode-remap-alist
;;   '((sh-mode         . bash-ts-mode)
;;     (c-mode          . c-ts-mode)
;;     (c++-mode        . c++-ts-mode)
;;     (c-or-c++-mode   . c-or-c++-ts-mode)
;;     (css-mode        . css-ts-mode)
;;     (js-mode         . js-ts-mode)
;;     (js-json-mode    . json-ts-mode)
;;     (makefile-mode   . cmake-ts-mode)
;;     (python-mode     . python-ts-mode)
;;     (ruby-mode       . ruby-ts-mode)
;;     (conf-toml-mode  . toml-ts-mode)))
;;   (setq treesit-language-source-alist
;;   '((bash       . ("https://github.com/tree-sitter/tree-sitter-bash"))
;;     (c          . ("https://github.com/tree-sitter/tree-sitter-c"))
;;     (cpp        . ("https://github.com/tree-sitter/tree-sitter-cpp"))
;;     (css        . ("https://github.com/tree-sitter/tree-sitter-css"))
;;     (cmake      . ("https://github.com/uyha/tree-sitter-cmake"))
;;     (dockerfile . ("https://github.com/camdencheek/tree-sitter-dockerfile"))
;;     (elisp      . ("https://github.com/Wilfred/tree-sitter-elisp"))
;;     (go         . ("https://github.com/tree-sitter/tree-sitter-go"))
;;     (gomod      . ("https://github.com/camdencheek/tree-sitter-go-mod.git"))
;;     (html       . ("https://github.com/tree-sitter/tree-sitter-html"))
;;     (javascript . ("https://github.com/tree-sitter/tree-sitter-javascript"))
;;     (json       . ("https://github.com/tree-sitter/tree-sitter-json"))
;;     (lua        . ("https://github.com/Azganoth/tree-sitter-lua"))
;;     (make       . ("https://github.com/alemuller/tree-sitter-make"))
;;     (markdown   . ("https://github.com/MDeiml/tree-sitter-markdown" nil "tree-sitter-markdown/src"))
;;     (org        . ("https://github.com/milisims/tree-sitter-org"))
;;     (python     . ("https://github.com/tree-sitter/tree-sitter-python"))
;;     (typescript . ("https://github.com/tree-sitter/tree-sitter-typescript" nil "typescript/src"))
;;     (tsx        . ("https://github.com/tree-sitter/tree-sitter-typescript" nil "tsx/src"))
;;     (ruby       . ("https://github.com/tree-sitter/tree-sitter-ruby"))
;;     (rust       . ("https://github.com/tree-sitter/tree-sitter-rust"))
;;     (sql        . ("https://github.com/m-novikov/tree-sitter-sql"))
;;     (vue        . ("https://github.com/merico-dev/tree-sitter-vue"))
;;     (yaml       . ("https://github.com/ikatyang/tree-sitter-yaml"))
;;     (toml       . ("https://github.com/tree-sitter/tree-sitter-toml"))
;;     (zig        . ("https://github.com/GrayJack/tree-sitter-zig")))))
#end_src

#+begin_src emacs-lisp
  (when (and (fboundp 'treesit-available-p) (treesit-available-p))

  ;; 设置更高的语法高亮级别
  (setq treesit-font-lock-level 4)

  ;; 重定向传统 major-mode 到对应的 tree-sitter 模式
  (setq major-mode-remap-alist
        '((sh-mode         . bash-ts-mode)
          (c-mode          . c-ts-mode)
          (c++-mode        . c++-ts-mode)
          (c-or-c++-mode   . c-or-c++-ts-mode)
          (css-mode        . css-ts-mode)
          (js-mode         . js-ts-mode)
          (js-json-mode    . json-ts-mode)
          (makefile-mode   . cmake-ts-mode)
          (python-mode     . python-ts-mode)
          (ruby-mode       . ruby-ts-mode)
          (conf-toml-mode  . toml-ts-mode)))

  ;; 指定源码仓库，用于 M-x treesit-install-language-grammar
  (setq treesit-language-source-alist
        '((bash       . ("https://github.com/tree-sitter/tree-sitter-bash"))
          (c          . ("https://github.com/tree-sitter/tree-sitter-c"))
          (cpp        . ("https://github.com/tree-sitter/tree-sitter-cpp"))
          (css        . ("https://github.com/tree-sitter/tree-sitter-css"))
          (cmake      . ("https://github.com/uyha/tree-sitter-cmake"))
          (dockerfile . ("https://github.com/camdencheek/tree-sitter-dockerfile"))
          (elisp      . ("https://github.com/Wilfred/tree-sitter-elisp"))
          (go         . ("https://github.com/tree-sitter/tree-sitter-go"))
          (gomod      . ("https://github.com/camdencheek/tree-sitter-go-mod.git"))
          (html       . ("https://github.com/tree-sitter/tree-sitter-html"))
          (javascript . ("https://github.com/tree-sitter/tree-sitter-javascript"))
          (json       . ("https://github.com/tree-sitter/tree-sitter-json"))
          (lua        . ("https://github.com/Azganoth/tree-sitter-lua"))
          (make       . ("https://github.com/alemuller/tree-sitter-make"))
          (markdown   . ("https://github.com/MDeiml/tree-sitter-markdown" nil "tree-sitter-markdown/src"))
          (org        . ("https://github.com/milisims/tree-sitter-org"))
          (python     . ("https://github.com/tree-sitter/tree-sitter-python"))
          (typescript . ("https://github.com/tree-sitter/tree-sitter-typescript" nil "typescript/src"))
          (tsx        . ("https://github.com/tree-sitter/tree-sitter-typescript" nil "tsx/src"))
          (ruby       . ("https://github.com/tree-sitter/tree-sitter-ruby"))
          (rust       . ("https://github.com/tree-sitter/tree-sitter-rust"))
          (sql        . ("https://github.com/m-novikov/tree-sitter-sql"))
          (vue        . ("https://github.com/merico-dev/tree-sitter-vue"))
          (yaml       . ("https://github.com/ikatyang/tree-sitter-yaml"))
          (toml       . ("https://github.com/tree-sitter/tree-sitter-toml"))
          (zig        . ("https://github.com/GrayJack/tree-sitter-zig"))))

  ;; 自动匹配文件名启用对应 tree-sitter 模式
  (add-to-list 'auto-mode-alist '("\\(?:Dockerfile\\(?:\\..*\\)?\\|\\.[Dd]ockerfile\\)\\'" . dockerfile-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.go\\'" . go-ts-mode))
  (add-to-list 'auto-mode-alist '("/go\\.mod\\'" . go-mod-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.rs\\'" . rust-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.ya?ml\\'" . yaml-ts-mode))

  ;; Go 缩进设置(不使用 tab,宽度 4)
  (add-hook 'go-ts-mode-hook
            (lambda ()
              (setq go-ts-mode-indent-offset 4)
              (setq tab-width 4)
              (setq indent-tabs-mode nil))))
#+end_src

** Citre
先进的 =Ctags= 前端。
注意：使用 =ctags= 时，针对 =C/C++= 项目，建议显式指明 ~--language=C,C++~ 而非单独的 =C= 或 =C++= ，否则可能不会生成有关头文件的 =file kind tag= 
#+begin_src emacs-lisp :tangle no
  (use-package citre
    :ensure t
    :hook
    (prog-mode . citre-mode)
    :bind (:map prog-mode-map
                ("C-x c j" . citre-jump+)
                ("C-x c k" . citre-jump-back+)
                ("C-x c p" . citre-peek)
                ("C-x c a" . citre-ace-peek)
                ("C-x c u" . citre-update-this-tags-file))
    :init
    (setq citre-auto-enable-citre-mode-modes '(prog-mode)
          citre-default-create-tags-file-location 'global-cache
          citre-use-project-root-when-creating-tags t
          citre-prompt-language-for-ctags-command t)
    (defun citre-jump+ ()
      "Jump to the definition of the symbol at point.
      Fallback to `xref-find-definitions'."
      (interactive)
      (condition-case _
          (citre-jump)
        (error (call-interactively #'xref-find-definitions))))

    (defun citre-jump-back+ ()
      "Go back to the position before last `citre-jump'.
      Fallback to `xref-go-back'."
      (interactive)
      (condition-case _
          (citre-jump-back)
        (error (if (fboundp #'xref-go-back)
                  (call-interactively #'xref-go-back)
                  ;; `xref-pop-marker-stack' is an obsolete function,use `xref-go-back' instead
                (call-interactively #'xref-go-back)))))
    :config
    (with-eval-after-load 'cc-mode (require 'citre-lang-c))
    )
#+end_src

** Direnv
NixOS 上需要开启此插件。如果不是 NixOS 则暂时停用。
#+begin_src emacs-lisp :tangle no
  (when sys/linux
    (use-package direnv
      :ensure nil
      :config
      (direnv-mode))
    )
#+end_src

** Ends
#+begin_src emacs-lisp
  (provide 'init-lang)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; init-lang.el ends here
#+end_src

